In [1]:
!python --version

Python 3.12.7

In [4]:
# !pip install polars

In [5]:
import polars as pl

In [7]:
# creating dat
df = pl.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})
df

shape: (3, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 4   │
│ 2   ┆ 5   │
│ 3   ┆ 6   │
└─────┴─────┘

In [9]:
df.shape

(3, 2)

In [10]:
df["a"]

shape: (3,)
Series: 'a' [i64]
[
	1
	2
	3
]

In [11]:
df.select(["a","b"])

shape: (3, 2)
┌─────┬─────┐
│ a   ┆ b   │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 4   │
│ 2   ┆ 5   │
│ 3   ┆ 6   │
└─────┴─────┘

In [15]:
df = df.with_columns((pl.col("a") +pl.col("b")).alias("c"))

In [16]:
df

shape: (3, 3)
┌─────┬─────┬─────┐
│ a   ┆ b   ┆ c   │
│ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╡
│ 1   ┆ 4   ┆ 5   │
│ 2   ┆ 5   ┆ 7   │
│ 3   ┆ 6   ┆ 9   │
└─────┴─────┴─────┘

In [18]:
df.group_by("a").agg(pl.col("c").mean().alias("mean_c"))

shape: (3, 2)
┌─────┬────────┐
│ a   ┆ mean_c │
│ --- ┆ ---    │
│ i64 ┆ f64    │
╞═════╪════════╡
│ 1   ┆ 5.0    │
│ 3   ┆ 9.0    │
│ 2   ┆ 7.0    │
└─────┴────────┘

In [20]:
df.sort("c", descending=True)

shape: (3, 3)
┌─────┬─────┬─────┐
│ a   ┆ b   ┆ c   │
│ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╡
│ 3   ┆ 6   ┆ 9   │
│ 2   ┆ 5   ┆ 7   │
│ 1   ┆ 4   ┆ 5   │
└─────┴─────┴─────┘

In [21]:
df2 = pl.DataFrame({"a": [1, 2, 3], "d": [7, 8, 9]})
df.join(df2,on="a", how="inner")

shape: (3, 4)
┌─────┬─────┬─────┬─────┐
│ a   ┆ b   ┆ c   ┆ d   │
│ --- ┆ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╪═════╡
│ 1   ┆ 4   ┆ 5   ┆ 7   │
│ 2   ┆ 5   ┆ 7   ┆ 8   │
│ 3   ┆ 6   ┆ 9   ┆ 9   │
└─────┴─────┴─────┴─────┘

In [22]:
#lazy loading

In [24]:
lazy_df = pl.scan_csv("https://ocw.mit.edu/courses/15-097-prediction-machine-learning-and-statistics-spring-2012/89d88c5528513adc4002a1618ce2efb0_iris.csv")
lazy_df